[build]
command = ""
publish = "src"

[[headers]]
for = "/*.js"
[headers.values]
Content-Type = "application/javascript; charset=utf-8"

[[headers]]
for = "/*.ts"
[headers.values]
Content-Type = "application/typescript; charset=utf-8"
